namePrefix: gke-
namespace: services
resources:
  - ../../helm-base
  - agent-service-account.yaml
  - kubectl-service-account.yaml

patches:
- target:
    kind: ConfigMap
    name: tom-jenkins
  path: plugins.yaml
- path: statefulset-patch.yaml
- target:
    kind: Service
    name: gitwebhookproxy
  patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 8081

patchesStrategicMerge:
  - nodeport-patch.yaml
  - backend-annotation-patch.yaml

configMapGenerator:
  - name: tom-jenkins-jenkins-jcasc-config
    namespace: helm-base
    behavior: merge
    files:
      - jcasc-default-config.yaml=jcasc.yaml
  - name: gitwebhookproxy
    behavior: merge
    envs:
    - gwp-config.env

secretGenerator:
  - name: tom-jenkins-auth
    envs:
    - jenkins-auth.env
  - name: gcp-sa
    files:
    - gcp-sa.json=gcp-sa.json
    options:
      disableNameSuffixHash: true
  - name: gitwebhookproxy
    behavior: merge
    envs:
    - gwp-secrets.env
