namePrefix: gke-
namespace: services
commonLabels:
  service: jenkins
resources:
  - ../../helm-base
  - service-accounts.yaml
  # - smee-client.yaml

patches:
- target:
    kind: ConfigMap
    name: tom-jenkins
  path: plugins.yaml
# - path: statefulset-patch.yaml

# patchesStrategicMerge:
#   - nodeport-patch.yaml
#   - backend-annotation-patch.yaml

# configMapGenerator:
#   - name: tom-jenkins-jenkins-jcasc-config
#     namespace: helm-base
#     behavior: merge
#     files:
#     - jcasc-default-config.yaml=jcasc.yaml
#   - name: tom-jenkins-tests
#     namespace: helm-base
#     behavior: merge
#     files:
#     - run.sh=startup-tests.sh
    
# secretGenerator:
#   - name: tom-jenkins-auth
#     envs:
#     - jenkins-auth.env
#   - name: gcp-sa
#     files:
#     - gcp-sa.json=gcp-sa.json
#     options:
#       disableNameSuffixHash: true
#   - name: smee-auth
#     envs:
#     - smee-auth.env
#     options:
#       disableNameSuffixHash: true
