apiVersion: v1
kind: Service
metadata:
  name: tom-jenkins
  namespace: helm-base
spec:
  type: NodePort
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gitwebhookproxy
# spec:
#   type: NodePort
