apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-sa
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-sa
subjects:
- kind: ServiceAccount
  name: agent-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubectl-sa
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubectl-sa
subjects:
  - kind: ServiceAccount
    name: kubectl-sa
