apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tom-jenkins
  namespace: helm-base
spec:
  template:
    spec:
      containers:
        - name: config-reload
          env:
            - name: NAMESPACE
              value: ""
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.namespace
