apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tom-jenkins
  namespace: helm-base
spec:
  template:
    spec:
      containers:
        - name: jenkins
          image: "jenkins/jenkins:lts-jdk11"
          volumeMounts:
            - mountPath: /run/secrets/jenkins-auth
              name: jenkins-auth
              readOnly: true
        - name: config-reload
          env:
            - name: NAMESPACE
              value: ""
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: jenkins-auth
          secret:
            secretName: gke-tom-jenkins-auth
